export const GET_APPS_SUCCESS = 'GET_APPS_SUCCESS'
export const GET_APPS_REQUEST = 'GET_APPS_REQUEST'
export const GET_APPS_FAILURE = 'GET_APPS_FAILURE'

export const GET_APP_SUCCESS = 'GET_APP_SUCCESS'
export const GET_APP_REQUEST = 'GET_APP_REQUEST'
export const GET_APP_FAILURE = 'GET_APP_FAILURE'

export const CREATE_APP_SUCCESS = 'CREATE_APP_SUCCESS'
export const CREATE_APP_REQUEST = 'CREATE_APP_REQUEST'
export const CREATE_APP_FAILURE = 'CREATE_APP_FAILURE'

export const GET_STATUS_SUCCESS = 'GET_STATUS_SUCCESS'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'



